#!/usr/bin/env bash
#
# Alacritty Terminal Adapter for voxr
# Implements apply_colors() and reload()
#

ALACRITTY_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty"
ALACRITTY_CONF="$ALACRITTY_CONFIG_DIR/alacritty.toml"
THEME_FILE="$ALACRITTY_CONFIG_DIR/current-theme.toml"

# Helper to extract a color key from the .conf file safely under pipefail
get_hex() {
  local file="$1"
  local key="$2"
  local val
  val="$(grep -E "^[[:space:]]*$key[[:space:]]+" "$file" 2>/dev/null | awk '{print $2}' | tr -d ' \r\n' || true)"
  echo "$val"
}

ensure_alacritty_include() {
  mkdir -p "$ALACRITTY_CONFIG_DIR"
  if [ ! -f "$ALACRITTY_CONF" ]; then
    echo 'import = ["current-theme.toml"]' > "$ALACRITTY_CONF"
  elif ! grep -Eq 'current-theme\.toml' "$ALACRITTY_CONF"; then
    printf "\n# Added by voxr\nimport = [\"current-theme.toml\"]\n" >> "$ALACRITTY_CONF"
  fi
}

apply_colors() {
  local scheme_file="$1"
  if [ ! -f "$scheme_file" ]; then
    echo "Error: Colorscheme file not found: $scheme_file" >&2
    return 1
  fi

  mkdir -p "$ALACRITTY_CONFIG_DIR"

  local bg fg cursor_bg cursor_fg sel_bg sel_fg
  bg="$(get_hex "$scheme_file" "background")"
  fg="$(get_hex "$scheme_file" "foreground")"
  cursor_bg="$(get_hex "$scheme_file" "cursor")"
  cursor_fg="$(get_hex "$scheme_file" "cursor_text_color")"
  sel_bg="$(get_hex "$scheme_file" "selection_background")"
  sel_fg="$(get_hex "$scheme_file" "selection_foreground")"

  # Standard 0-7
  local c0 c1 c2 c3 c4 c5 c6 c7
  c0="$(get_hex "$scheme_file" "color0")"
  c1="$(get_hex "$scheme_file" "color1")"
  c2="$(get_hex "$scheme_file" "color2")"
  c3="$(get_hex "$scheme_file" "color3")"
  c4="$(get_hex "$scheme_file" "color4")"
  c5="$(get_hex "$scheme_file" "color5")"
  c6="$(get_hex "$scheme_file" "color6")"
  c7="$(get_hex "$scheme_file" "color7")"

  # Bright 8-15
  local c8 c9 c10 c11 c12 c13 c14 c15
  c8="$(get_hex "$scheme_file" "color8")"
  c9="$(get_hex "$scheme_file" "color9")"
  c10="$(get_hex "$scheme_file" "color10")"
  c11="$(get_hex "$scheme_file" "color11")"
  c12="$(get_hex "$scheme_file" "color12")"
  c13="$(get_hex "$scheme_file" "color13")"
  c14="$(get_hex "$scheme_file" "color14")"
  c15="$(get_hex "$scheme_file" "color15")"

  # Generate Alacritty TOML format
  cat > "$THEME_FILE" <<EOF
# Generated by voxr for Alacritty
[colors.primary]
background = "${bg:-#000000}"
foreground = "${fg:-#ffffff}"

[colors.cursor]
text = "${cursor_fg:-${bg:-#000000}}"
cursor = "${cursor_bg:-${fg:-#ffffff}}"

[colors.selection]
text = "${sel_fg:-${fg:-#ffffff}}"
background = "${sel_bg:-${c8:-#555555}}"

[colors.normal]
black   = "${c0:-#000000}"
red     = "${c1:-#cc0000}"
green   = "${c2:-#00cc00}"
yellow  = "${c3:-#cccc00}"
blue    = "${c4:-#0000cc}"
magenta = "${c5:-#cc00cc}"
cyan    = "${c6:-#00cccc}"
white   = "${c7:-#cccccc}"

[colors.bright]
black   = "${c8:-#555555}"
red     = "${c9:-#ff5555}"
green   = "${c10:-#55ff55}"
yellow  = "${c11:-#ffff55}"
blue    = "${c12:-#5555ff}"
magenta = "${c13:-#ff55ff}"
cyan    = "${c14:-#55ffff}"
white   = "${c15:-#ffffff}"
EOF

  ensure_alacritty_include

  echo "Applied to Alacritty configuration ($THEME_FILE)."
  echo "Alacritty live-reloads automatically if live configuration reload is enabled."
  return 0
}

reload() {
  # Alacritty watches config file via notify/inotify automatically
  touch "$THEME_FILE" 2>/dev/null || true
  echo "Touched Alacritty theme configuration to trigger reload."
}
