#!/usr/bin/env bash
#
# Foot Terminal Adapter for voxr
# Implements apply_colors() and reload()
# NOTE: Foot format requires hex color codes WITHOUT '#' (e.g. ff00aa)
#

FOOT_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/foot"
FOOT_CONF="$FOOT_CONFIG_DIR/foot.ini"
THEME_FILE="$FOOT_CONFIG_DIR/current-theme.ini"

# Helper to extract a color key from the .conf file and strip the '#' character safely under pipefail
get_raw_hex() {
  local file="$1"
  local key="$2"
  local val
  val="$(grep -E "^[[:space:]]*$key[[:space:]]+" "$file" 2>/dev/null | awk '{print $2}' | tr -d ' \r\n' || true)"
  echo "${val#"#"}"
}

ensure_foot_include() {
  mkdir -p "$FOOT_CONFIG_DIR"
  local abs_theme="$THEME_FILE"

  if [ ! -f "$FOOT_CONF" ]; then
    echo "include=$abs_theme" > "$FOOT_CONF"
    return 0
  fi

  # If foot.ini has the relative include=current-theme.ini, replace it with the absolute path
  if grep -Eq '^[[:space:]]*include[[:space:]]*=[[:space:]]*(\./)?current-theme\.ini' "$FOOT_CONF"; then
    sed -i -E "s|^[[:space:]]*include[[:space:]]*=[[:space:]]*(\./)?current-theme\.ini|include=$abs_theme|" "$FOOT_CONF"
  elif ! grep -Fq "include=$abs_theme" "$FOOT_CONF"; then
    printf "\n# Added by voxr\ninclude=%s\n" "$abs_theme" >> "$FOOT_CONF"
  fi
}

apply_colors() {
  local scheme_file="$1"
  if [ ! -f "$scheme_file" ]; then
    echo "Error: Colorscheme file not found: $scheme_file" >&2
    return 1
  fi

  mkdir -p "$FOOT_CONFIG_DIR"

  local bg fg sel_bg sel_fg
  bg="$(get_raw_hex "$scheme_file" "background")"
  fg="$(get_raw_hex "$scheme_file" "foreground")"
  sel_bg="$(get_raw_hex "$scheme_file" "selection_background")"
  sel_fg="$(get_raw_hex "$scheme_file" "selection_foreground")"

  # Standard regular 0-7
  local r0 r1 r2 r3 r4 r5 r6 r7
  r0="$(get_raw_hex "$scheme_file" "color0")"
  r1="$(get_raw_hex "$scheme_file" "color1")"
  r2="$(get_raw_hex "$scheme_file" "color2")"
  r3="$(get_raw_hex "$scheme_file" "color3")"
  r4="$(get_raw_hex "$scheme_file" "color4")"
  r5="$(get_raw_hex "$scheme_file" "color5")"
  r6="$(get_raw_hex "$scheme_file" "color6")"
  r7="$(get_raw_hex "$scheme_file" "color7")"

  # Bright 8-15 -> bright0 to bright7
  local b0 b1 b2 b3 b4 b5 b6 b7
  b0="$(get_raw_hex "$scheme_file" "color8")"
  b1="$(get_raw_hex "$scheme_file" "color9")"
  b2="$(get_raw_hex "$scheme_file" "color10")"
  b3="$(get_raw_hex "$scheme_file" "color11")"
  b4="$(get_raw_hex "$scheme_file" "color12")"
  b5="$(get_raw_hex "$scheme_file" "color13")"
  b6="$(get_raw_hex "$scheme_file" "color14")"
  b7="$(get_raw_hex "$scheme_file" "color15")"

  cat > "$THEME_FILE" <<EOF
# Generated by voxr for Foot
# Note: Foot requires hex values without the leading '#' symbol
[colors]
background=${bg:-000000}
foreground=${fg:-ffffff}
regular0=${r0:-000000}
regular1=${r1:-cc0000}
regular2=${r2:-00cc00}
regular3=${r3:-cccc00}
regular4=${r4:-0000cc}
regular5=${r5:-cc00cc}
regular6=${r6:-00cccc}
regular7=${r7:-cccccc}

bright0=${b0:-555555}
bright1=${b1:-ff5555}
bright2=${b2:-55ff55}
bright3=${b3:-ffff55}
bright4=${b4:-5555ff}
bright5=${b5:-ff55ff}
bright6=${b6:-55ffff}
bright7=${b7:-ffffff}

${sel_bg:+selection-target=${sel_bg}}
${sel_fg:+selection-foreground=${sel_fg}}
EOF

  ensure_foot_include

  echo "Applied to Foot configuration ($THEME_FILE)."
  echo "Foot automatically reloads its configuration."
  return 0
}

reload() {
  touch "$THEME_FILE" 2>/dev/null || true
  echo "Touched Foot theme configuration to trigger reload."
}
