#!/usr/bin/env bash
#
# Ghostty Terminal Adapter for voxr
# Implements apply_colors() and reload()
#

GHOSTTY_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty"
GHOSTTY_CONF="$GHOSTTY_CONFIG_DIR/config"
THEME_FILE="$GHOSTTY_CONFIG_DIR/current-theme"

# Helper to extract a color key from the .conf file safely under pipefail
get_hex() {
  local file="$1"
  local key="$2"
  local val
  val="$(grep -E "^[[:space:]]*$key[[:space:]]+" "$file" 2>/dev/null | awk '{print $2}' | tr -d ' \r\n' || true)"
  echo "$val"
}

ensure_ghostty_include() {
  mkdir -p "$GHOSTTY_CONFIG_DIR"
  if [ ! -f "$GHOSTTY_CONF" ]; then
    echo "config-file = current-theme" > "$GHOSTTY_CONF"
  elif ! grep -Eq 'config-file[[:space:]]*=[[:space:]]*(.+/)?current-theme' "$GHOSTTY_CONF"; then
    printf "\n# Added by voxr\nconfig-file = current-theme\n" >> "$GHOSTTY_CONF"
  fi
}

apply_colors() {
  local scheme_file="$1"
  if [ ! -f "$scheme_file" ]; then
    echo "Error: Colorscheme file not found: $scheme_file" >&2
    return 1
  fi

  mkdir -p "$GHOSTTY_CONFIG_DIR"

  local bg fg cursor_bg cursor_fg sel_bg sel_fg
  bg="$(get_hex "$scheme_file" "background")"
  fg="$(get_hex "$scheme_file" "foreground")"
  cursor_bg="$(get_hex "$scheme_file" "cursor")"
  cursor_fg="$(get_hex "$scheme_file" "cursor_text_color")"
  sel_bg="$(get_hex "$scheme_file" "selection_background")"
  sel_fg="$(get_hex "$scheme_file" "selection_foreground")"

  # Write Ghostty configuration
  {
    echo "# Generated by voxr for Ghostty"
    echo "background = ${bg:-#000000}"
    echo "foreground = ${fg:-#ffffff}"
    [ -n "$cursor_bg" ] && echo "cursor-color = $cursor_bg"
    [ -n "$cursor_fg" ] && echo "cursor-text = $cursor_fg"
    [ -n "$sel_bg" ] && echo "selection-background = $sel_bg"
    [ -n "$sel_fg" ] && echo "selection-foreground = $sel_fg"

    for i in {0..15}; do
      local c
      c="$(get_hex "$scheme_file" "color$i")"
      if [ -n "$c" ]; then
        echo "palette = $i=$c"
      fi
    done
  } > "$THEME_FILE"

  ensure_ghostty_include

  echo "Applied to Ghostty configuration ($THEME_FILE)."
  echo "Ghostty reloads configuration automatically upon file changes."
  return 0
}

reload() {
  touch "$THEME_FILE" 2>/dev/null || true
  echo "Touched Ghostty configuration to trigger reload."
}
